"""Export the in-memory KG as a Neo4j load script (Cypher CREATE statements)."""
from __future__ import annotations

import json
from pathlib import Path

from .kg import KG


def _props(d: dict) -> str:
    items = []
    for k, v in d.items():
        if v is None or v == "" or v == []:
            continue
        items.append(f"{k}: {json.dumps(v, ensure_ascii=False)}")
    return "{" + ", ".join(items) + "}"


def export(kg: KG, out: str | Path) -> Path:
    lines = ["// Generated by `kgdiet export-cypher`. Load with: cypher-shell -f load.cypher",
             "MATCH (n) DETACH DELETE n;"]
    labels = sorted({n["label"] for n in kg.nodes.values()})
    for label in labels:
        key = "id"
        lines.append(f"CREATE CONSTRAINT {label.lower()}_id IF NOT EXISTS FOR (n:{label}) REQUIRE n.{key} IS UNIQUE;")
    for nid, n in kg.nodes.items():
        props = {k: v for k, v in n.items() if k not in ("label", "key")}
        props["id"] = n["key"]
        lines.append(f"CREATE (:{n['label']} {_props(props)});")
    for src, edges in kg.out_edges.items():
        for e in edges:
            sl, sk = src.split(":", 1)
            dl, dk = e.dst.split(":", 1)
            lines.append(f"MATCH (a:{sl} {{id: {json.dumps(sk)}}}), (b:{dl} {{id: {json.dumps(dk)}}}) "
                         f"CREATE (a)-[:{e.type} {_props(e.props)}]->(b);")
    path = Path(out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
